version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dbPractica
    environment:
      - POSTGRES_DB=my_mb
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
